### ISSUE TITLE
1 - Display Rebate

### ISSUE THREAD

**Issue by julesainbolt** [Sakezone/team-blank-CS1C#14]
Priority: Medium
Story Point estimation: 1

# Story
As a store manager, I should be able to view the rebate of all the Executive members, so I know how much money they get back.

# Assumptions
- Story #9 - Display Total Purchases Per Member is completed.
- Story #3 - Member List is completed.

# Description
On the member list display, there's a column called rebate and it should be sorted by the members id for Executive members.

# Tasks
- [ ] Compute the rebate
- [ ] Display the rebate
- [ ] Update the rebate

# Source(s)
Source coming from bullet point 4 from the project doc.
"A store manager should be able to display the rebate of all the Executive members sorted by membership number."

# Definition of Done
The member list should display the rebate sorted by Executive members id.
