### ISSUE TITLE
Program Check List

### ISSUE THREAD

**Issue by ocboogie** [Sakezone/team-blank-CS1C#6]
- [x] #8  A store manager should be able to display a sales report for any given day. It should include a list of items and quantities sold on that day as well names of the members who shopped that day.  Display the total revenue for the given day.  It should also include number of Executive members and Regular members who shopped during the given day.  Your team should provide an option to generate the display by membership type.
- [x] #9 A store manager should be able to display the total purchases for each member sorted by membership number.  The display should also include a grand total of all the purchases for all the members.
- [x] #2 A store manager should be able to display the quantity of each item sold sorted by item name and the total revenue for each item.
- [x] #14 A store manager should be able to display the rebate of all the Executive members sorted by membership number.
- [x] #11 A store manager should be able to enter a month and obtain a display of all members whose memberships expire that month as well as the cost to renew their memberships.
- [x] #7 An administrator should be able to add/delete Bulk Club members.
- [x] #10 Your team should provide the capability to create purchases for the new members to validate your software.
- [x] #13 An administrator should be able to add (with a corresponding price), delete items, and change prices from the inventory list.
- [x] #2 A store manager should be able to enter an item name and display the quantity of that item sold as well as the total revenue for the item.
- [x] #9 A store manager should be able to enter a membership number __or__ name and display the total purchases for that member.
- [x] #16 Your program should be able to determine if any Regular customer should convert their membership to Executive status. Display the number of recommended conversions.
- [x] #16 An administrator should be able to determine if any Executive customer should convert their membership to Regular status. Display the number of recommended conversions.
- [X] #1 Your software should require the store manager and administrator to logon to obtain access to your program.
- [x] Your software should be able to save all changes between executions.
