### ISSUE TITLE
1 - Display Total Purchases Per Member

### ISSUE THREAD

**Issue by julesainbolt** [Sakezone/team-blank-CS1C#9]
Priority: Medium
Story Point estimation: 1

# Story
As a store manager, I should be able to view the total number of purchases for each member, so that I'm able to see how business is doing and to keep track of our profits.

# Assumptions
- Story #5 - Inventory List is completed.

# Description
Add a tab to the main window and once clicked, a window will be displayed showing members purchases sorted by their membership number. 

# Tasks
- [x] Add a tab to the main menu
- [x] Create the display for the members purchases sorted by membership number

# Source(s)
Source coming from bullet point 2 from the project doc.
"A store manager should be able to display the total purchases for each member sorted by membership number. The display should also include a grand total of all the purchases for all the members."

# Definition of Done
When the tab is clicked, the display of all the members purchases sorted by membership number will appear.

**Comment by julesainbolt** [comment]
Story: TODO
Priority Assumption: TODO

# Story

As a store manager, I should be able to view the total number of purchases for each member as well as the total of all the purchases for all the members. 

# Assumptions

Main Window is completed.

# Description

Add a tab to the main window and once clicked, a window will be displayed showing members purchases sorted by their membership number.

# Tasks

- [ ] Add a tab to the main menu

- [ ]  Once clicked, a dialog box would open up prompting the store manager to enter in the members name or number

- [ ] Create the display for the members purchases sorted by membership number
- [ ] Create the display for the total purchases for all members

# Definition of Done

When the button is clicked, a dialog box is displayed, allowing the store manager to enter in the members name or number. When they hit Ok, their purchases will be displayed by their membership number, as well as the total purchases for all the members.

**Comment by julesainbolt** [comment]
Finished user story 3.
